### ISSUE TITLE
Problem reproducing minimal example

### ISSUE THREAD

**Issue by clessig** [pytorch/tau#752]
I wanted to reproduce the minimal example that is provided. However, I get the following error:

>>> import torch
>>> torch.__version__
'1.12.0'
>>> from pippy.IR import Pipe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/p/project/atmo-rep/lessig/atmorep/atmorep/lessig-full-config/atmorep/torch/scratch/tau/pippy/__init__.py", line 2, in <module>
    from pippy.IR import (
  File "/p/project/atmo-rep/lessig/atmorep/atmorep/lessig-full-config/atmorep/torch/scratch/tau/pippy/IR.py", line 12, in <module>
    from pippy.fx.passes.split_module import split_module
  File "/p/project/atmo-rep/lessig/atmorep/atmorep/lessig-full-config/atmorep/torch/scratch/tau/pippy/fx/passes/__init__.py", line 7, in <module>
    from . import reinplace
  File "/p/project/atmo-rep/lessig/atmorep/atmorep/lessig-full-config/atmorep/torch/scratch/tau/pippy/fx/passes/reinplace.py", line 5, in <module>
    from torch._subclasses.fake_tensor import FakeTensorMode, FakeTensor
ModuleNotFoundError: No module named 'torch._subclasses'

I don't use a nightly build of pytorch 1.12 and it's not easily an option for me (I am on a big compute cluster where there are optimized packages available).

**Comment by ashe-shi** [comment]
> 

I have the same error, using Pytorch 1.12. 
And currently dev version seems unavailable:

```
ERROR: Could not find a version that satisfies the requirement torch==1.12.0.dev0 (from versions: 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0.dev20220809+cu116, 1.13.0.dev20220810+cu116, 1.13.0.dev20220811+cu116, 1.13.0.dev20220812+cu116, 1.13.0.dev20220813+cu116, 1.13.0.dev20220814+cu116
```

**Comment by kwen2501** [comment]
Thanks @clessig and @ashe-shi for reporting this issue.

It seems `torch._subclasses` is not introduced till PyTorch 1.13.0, hence the error you see.

I will update PiPPy's requirements file to reflect this. That is, changing from
```
torch >= 1.12.0.dev0
```
to
```
torch >= 1.13.0
```

Meanwhile, please upgrade the PyTorch version in your environment to bypass this issue. 
Thank you!
